#!/bin/bash

#SBATCH --time=01:00:00
#SBATCH --partition=west
#SBATCH --nodes=6 --tasks-per-node=2
#SBATCH --error=COMMUNICATION_A_GS_6_10_200.err --output=COMMUNICATION_A_GS_6_10_200.out

. /etc/profile.d/wr-spack.sh
spack load --dependencies mpi

export MPICH_NEMESIS_NETMOD=tcp

mpiexec -n 10 ./partdiff-par 1 1 200 1 1 3.3504e-05
mpiexec -n 10 ./partdiff-par 1 1 200 1 1 3.3504e-05
mpiexec -n 10 ./partdiff-par 1 1 200 1 1 3.3504e-05
